name: Manual Release
on:
  workflow_dispatch:
    inputs:
      name:
        description: "Release-Build"
        default: "Generate release build"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checking out branch
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Decode Keystore
        run: |
          base64 -d ${{ secrets.KEYSTORE_BASE64 }} > keystore.jks

      - name: Build with Gradle
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        run: |
          ./gradlew clean assembleRelease
          cd app/build/outputs/apk/release && mv app-release.apk BanUninstall.apk

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: release
          path: app/build/outputs/apk/release/*.apk